services:
  traefik:
    image: traefik:v2.11
    restart: always
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network
    labels:
      - "traefik.enable=true"

  neo4j:
    image: neo4j:5.22.0-community
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
    networks:
      - app_network

  prensa:
    image: nginx:alpine
    restart: always
    networks:
      - app_network
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prensa.rule=Host(`prensa.localhost`)"
      - "traefik.http.routers.prensa.entrypoints=web"
      - "traefik.http.services.prensa.loadbalancer.server.port=80"

volumes:
  neo4j_data:
    driver: local

networks:
  app_network:
    driver: bridge

